### ISSUE TITLE
How to apply this patch to the kernel 6.2.6?

### ISSUE THREAD

**Issue by ywiyogo** [codepayne/pop-os-linux#6]
I have a Huawei D16 AMD 2021 and already installed the pop-os 22.04. I just realized these issues after I replaced the content in my SSD and can't go back to the original Windows anymore :(.

Since the patch is based on the 6.0.2 kernel version. How can I apply those commits on my laptop with kernel 6.2.6?
The outout of `uname -a`: 
```
Linux pop-os 6.2.6-76060206-generic #202303130630~1679424972~22.04~4a8cde1 SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux
```
I found these files inside /usr/src:
```
root@pop-os:~# ls /usr/src/
linux-headers-6.2.6-76060206          system76-1.0.14~1643391291~22.04~78ede46
linux-headers-6.2.6-76060206-generic  system76_acpi-1.0.2~1678132042~22.04~ed01124
linux-source-5.15.0                   system76-io-1.0.2~1655490480~22.04~0217576
linux-source-5.15.0.tar.bz2
```

The outputs from the `dmidecode` shows
```
Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: HUAWEI
	Product Name: HVY-WXX9
	Version: M1020
```
which is already in the commit https://github.com/codepayne/pop-os-linux/commit/8eb701061b5815f199374b99fb7b9cfc8f853bc1.

Is the linux-source-5.15.0 on my laptop is the correct one? If not how can I download the linux-source-6.2.6?
I would like to apply the patch by executing `git cherry-pick xxx`, and build it with `make -j $(nproc) && sudo make install`.

**Comment by ghost** [comment]
I'm interested in this too, how to isolate changes from this repo and apply them to other kernel versions? It would be nice if it's possible.

Also can you please open a pr to the mainline kernel? It's not really safe to sit on a fork of a kernel without frequent updates, bit now we have this sad choice of either having a sound support, or the latest kernel updates, including security ones.

**Comment by shmsh9** [comment]
I compiled two patches from @codepayne commits : 
    https://aur.archlinux.org/cgit/aur.git/tree/0003-es8316.patch?h=linux-lts-huawei-amd-audio
    https://aur.archlinux.org/cgit/aur.git/tree/0002-huawei-amd-sound.patch?h=linux-lts-huawei-amd-audio

They have been working on all the 6.1 releases I tried maybe you'll get lucky too

**Comment by sanek2** [comment]
I tried patch on kernel 6.3.5. No acp3x-es83xx in alsamixer and no sound and no mic.
But on kernel 6.3.5 without patch I have working mic, but no sound.
Using current repository kernel I have sound but the microphone is recording white noise.

**Comment by ywiyogo** [comment]
Thanks @shmsh9, however, I've already sold my laptop, and I use rather a Linux friendly laptop.

**Comment by shmsh9** [comment]
> I tried patch on kernel 6.3.5. No acp3x-es83xx in alsamixer and no sound and no mic. But on kernel 6.3.5 without patch I have working mic, but no sound. Using current repository kernel I have sound but the microphone is recording white noise.

Hi @sanek2 you can try [this new one](https://gist.githubusercontent.com/shmsh9/8ef31f2d13ce0a31c031043c57e8ed67/raw/1cb35362fc8a292f121bb1ffacbe0e2f6c06da2c/linux-6.4.2.huawei-amd-sound.patch) works for me on 6.4.2 (arch)

**Comment by imagoillusion** [comment]
> > I tried patch on kernel 6.3.5. No acp3x-es83xx in alsamixer and no sound and no mic. But on kernel 6.3.5 without patch I have working mic, but no sound. Using current repository kernel I have sound but the microphone is recording white noise.
> 
> Hi @sanek2 you can try [this new one](https://gist.githubusercontent.com/shmsh9/8ef31f2d13ce0a31c031043c57e8ed67/raw/1cb35362fc8a292f121bb1ffacbe0e2f6c06da2c/linux-6.4.2.huawei-amd-sound.patch) works for me on 6.4.2 (arch)

Hi @shmsh9 Can you be so nice to explain how to use that diff file to patch arch kernel. I have sound on @codepayne popOS but i will realy like to have that on new kernel....thank you!

**Comment by shmsh9** [comment]
Hi @imagoillusion 
You need to install [linux-lts-huawei-amd-audio](https://aur.archlinux.org/packages/linux-lts-huawei-amd-audio) or [linux-huawei-amd-audio](https://aur.archlinux.org/packages/linux-huawei-amd-audio) from the aur and then figure out how to add it to your bootloader entries
