### ISSUE TITLE
Installation on PopOS 22.04 failed due to not enough disk space in /boot/efi

### ISSUE THREAD

**Issue by ywiyogo** [codepayne/pop-os-linux#7]
I ran these commands 
```
make -j$(nproc)
sudo make modules_install
sudo make install
```
Afterward the output of `sudo kernelstub -p` still points my default 6.2.6 kernel. I tried the command `sudo kernel-install add` and it shows the error that there is no more space in /boot/efi after the `sudo make install`. Total disk space of the partition /boot/efi is 1.1 GB.

How did you install this kernel in PopOS then?

**Comment by sanek2** [comment]
Try to set env variable INSTALL_MOD_STRIP to make kernel and modules lighter 
```

make modules_install INSTALL_MOD_STRIP=1
make install
```
